name: PR Commenter

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment to the PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for your contribution! Please wait for the reviewer to check your PR."
            })
